### ISSUE TITLE
Create docker for Litentry's integritee node

### ISSUE THREAD

**Issue by suinuj** [litentry/worker#59]
### Context
In the integration test, we found it failed. the root cause is the node still used from integritee repo, which not match with our worker.

### Task
- [x] Create docker for integrate node in litentry's repo
- [x] Update the image in worker

### Acceptance criteria
- [x] Integration test passed in CI

**Comment by suinuj** [comment]
close it after pr merged.
