### ISSUE TITLE
Account-linker migration - the enclave side

### ISSUE THREAD

**Issue by h4n0** [litentry/worker#8]
**Description**
Migrate the main functionality of the current account-linker to the enclave.

**Acceptance Criteria**
- [x] A new pallet with the name of account-linker-enclave or similar in litentry-pallets
- [x]  litentry/litentry-pallets#89
- [x] #9
- [x] #11
- [x] Include this in the worker repository and build (blocked by the tasks above)

**Comment by suinuj** [comment]
All tasks are done.
